### ISSUE TITLE
Enviroment variable to disable system-deps

### ISSUE THREAD

**Issue by mrbenshef** [gdesmott/system-deps#10]
I am using [gvsbuild](https://github.com/wingtk/gvsbuild) to compile a gtk application on windows (I have other dependencys that won't compile under MSYS). Before the gtk-rs release a few weeks ago I could compile with:

```powershell
${Env:RUSTFLAGS} = "-L C:\gtk-build\gtk\x64\release\lib"; cargo build
```

Now that gtk-rs uses system-deps I have to disable each dependency individually, which results in:

```powershell
${Env:SYSTEM_DEPS_glib_2_0_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_glib_2_0_LIB} = "glib-2.0"; 
${Env:SYSTEM_DEPS_cairo_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_cairo_LIB} = "cairo"; 
${Env:SYSTEM_DEPS_cairo_gobject_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_cairo_gobject_LIB} = "cairo-gobject"; 
${Env:SYSTEM_DEPS_gobject_2_0_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_gobject_2_0_LIB} = "gobject-2.0"; 
${Env:SYSTEM_DEPS_atk_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_atk_LIB} = "atk-1.0"; 
${Env:SYSTEM_DEPS_pango_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_pango_LIB} = "pango-1.0"; 
${Env:SYSTEM_DEPS_gio_2_0_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_gio_2_0_LIB} = "gio-2.0"; 
${Env:SYSTEM_DEPS_gdk_pixbuf_2_0_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_gdk_pixbuf_2_0_LIB} = "gdk_pixbuf-2.0"; 
${Env:SYSTEM_DEPS_gdk_3_0_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_gdk_3_0_LIB} = "gdk-3.0"; 
${Env:SYSTEM_DEPS_gtk+_3_0_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_gtk+_3_0_LIB} = "gtk-3.0"; 
${Env:SYSTEM_DEPS_GTK+_3.0_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_GTK+_3.0_LIB} = "gtk-3.0"; 
${Env:SYSTEM_DEPS_gtk_3_0_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_gtk_3_0_LIB} = "gtk-3.0"; 
${Env:SYSTEM_DEPS_GTK_3.0_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_GTK_3.0_LIB} = "gtk-3.0"; 
${Env:RUSTFLAGS} = "-L C:\gtk-build\gtk\x64\release\lib"; 
cargo build
```

Would it be possible to add somthing like `SYSTEM_DEPS_DISABLE`?

**Comment by gdesmott** [comment]
@sdroege : how do you think we should handle this?

**Comment by sdroege** [comment]
I don't know, from somewhere all the library names have to come from. That's the main problem here.

The official gtk way of doing that are the PKG-config files, and it seems like a bug to me that gvsbuild does not include them. If you used the meson build system included in gtk you could build with msvc and get those.

Maybe @nirbheek has a suggestion?

**Comment by nirbheek** [comment]
I thought gvsbuild shipped pkgconfig files? @nacho if it doesn't, shouldn't it ship pkgconfig files?

**Comment by nacho** [comment]
We definitely ship pkgconfig files...

**Comment by gdesmott** [comment]
Then it should just work. Have you tried tweaking your `PKG_CONFIG_PATH`?

**Comment by nirbheek** [comment]
Does gvsbuild ship with pkg-config? Is it built with `--define-prefix` enabled by default? If so, it should not need any PKG_CONFIG_PATH tweaking. We do that in gstreamer and it works well.

**Comment by nacho** [comment]
If I recall correct gvsbuild ships pkgconf, which should deal properly with --define-prefix. Maybe double check that all the pc files are in place and if some is missing let me know and I will add them

**Comment by mrbenshef** [comment]
Ah, this is prehaps more complicated than I though 😅. 

If I add `C:\gtk-build\gtk\x64\release\bin` to `Path` I get:

```
Package gtksourceview-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtksourceview-3.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtksourceview-3.0', required by 'virtual:world', not found
Package 'gtksourceview-3.0', required by 'virtual:world', not found
```

It doesn't look like `gtksourceview-3.0.pc` is anywhere in the gtk-build directory. Seems like this is the only one missing though, because I can build with:

```powershell
${Env:GTKSOURCEVIEW_3.0_NO_PKG_CONFIG} = 1; 
${Env:SYSTEM_DEPS_GTKSOURCEVIEW_3.0_LIB} = "gtksourceview-3.0"; 
cargo build
```

**Comment by nacho** [comment]
Do you need gtksourceview? If yes, note that we have not updated gsv for years. You might need to first update it in gvsbuild.

**Comment by nirbheek** [comment]
Latest [gtksourceview](https://gitlab.gnome.org/GNOME/gtksourceview) is [4.6.1](https://ftp.gnome.org/pub/gnome/sources/gtksourceview/4.6/) which supports meson, so it shouldn't be too hard to update it.

**Comment by mrbenshef** [comment]
The gtk-rs bindings are for sourceview 3, although I see there is a crate for sourview 4. I have to admit, this is a bit out of my league. My build command is a bit more sensible now, so feel free to close this.

**Comment by gdesmott** [comment]
Closing then, I don't think it makes much sense to disable `system-deps` completely.
