### ISSUE TITLE
Environment variable override to request building the C dependency as part of the crate for crates that support this

### ISSUE THREAD

**Issue by sdroege** [gdesmott/system-deps#2]
`METADEPS_${DEPENDENCY_NAME}_BUILD_INTERNAL` or similar. This would have to come with a hook in `build.rs` or so, so that metadeps can a) error out if not supported by the crate, b) call into crate specific code for actually building.

The crate specific code then has to provide CFLAGS, LIBS, LDFLAGS etc back to metadeps.

As part of this it would also be useful to make it an error if two crates in the dependency chain build the same library.

**Comment by gdesmott** [comment]
Do you know a crate doing this "properly" (or at least not too badly) which could be a good starting point to implement this feature?

**Comment by sdroege** [comment]
`dav1d`

**Comment by gdesmott** [comment]
That's the one I was looking. Just submit https://github.com/rust-av/dav1d-rs/pull/31 :)

**Comment by sdroege** [comment]
There's also https://github.com/rust-av/dav1d-rs/issues/26, which is loosely relevant here

**Comment by gdesmott** [comment]
From this thread it was suggested to have a `{auto,always,never}` switch.

So I guess we'd want  `METADEPS_${DEPENDENCY_NAME}_BUILD_INTERNAL={auto,always,never}`?

Not sure about the default, `auto` makes things more convenient but one may accidentally end up statically linking because her installed version is older for example.
Currently internal build is usually gated with an explicit feature so maybe `never` would make more sense as default.

**Comment by sdroege** [comment]
I agree about the default, yes. `never`

**Comment by gdesmott** [comment]
Here is what I have so far:

```rust
    pub fn add_build_internal<F>(&mut self, name: &str, func: F) -> &mut Self
    where
        F: 'static + FnOnce(&str) -> Library,
```

It works but the closure could fail so should return a `Result`. I'm not sure about the error type I should use. I tried `Result<Library, dyn error::Error>` but got a Sized error:

```
error[E0277]: the size for values of type `(dyn std::error::Error + 'static)` cannot be known at compilation time
  --> src/lib.rs:67:5
   |
67 |     build_internals: HashMap<String, Box<dyn FnOnce() -> std::result::Result<Library, dyn error::Error>>>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `(dyn std::error::Error + 'static)`
   = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
   = note: required by `std::result::Result`
```

How would you handle that?

**Comment by sdroege** [comment]
`Box<dyn Error>` would work, for example. But what do you want to do with that value? You probably want a small enum with a couple of variants for how things could possibly fails plus a string to print details.

**Comment by gdesmott** [comment]
I was wondering if we should allow users to report any `Error` or limit ourself with a few enum variants. I don't have much experience in this kind of API design, so I'll go with the latter if you think that's best. :)

**Comment by sdroege** [comment]
The question is how *you* would handle arbitrary errors :) It's you calling the callbacks so you need to do something with the results.

In addition to the enum it would make sense to also add a slot in each value for passing a "source": https://doc.rust-lang.org/nightly/std/error/trait.Error.html#method.source

There users of the API could return their own things as needed.

**Comment by gdesmott** [comment]
What would be the type of the source then? I tried `Box<dyn std::error::Error>` but got this failure:

```
error[E0277]: `(dyn std::error::Error + 'static)` cannot be sent between threads safely
  --> src/lib.rs:40:1
   |
40 | / error_chain! {
41 | |     foreign_links {
42 | |         PkgConfig(pkg_config::Error) #[doc="pkg-config error"];
43 | |         BuildInternalClosureError(BuildInternalClosureError) #[doc="build internal closure failure"];
...  |
74 | |     }
75 | | }
   | |_^ `(dyn std::error::Error + 'static)` cannot be sent between threads safely
   |
   = help: the trait `std::marker::Send` is not implemented for `(dyn std::error::Error + 'static)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `BuildInternalClosureError`
   = note: required because it appears within the type `ErrorKind`
   = note: required because it appears within the type `Error`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Full code is here: https://github.com/gdesmott/metadeps/commits/build

**Comment by gdesmott** [comment]
I think I'm mostly done with this feature: https://github.com/gdesmott/metadeps/commits/build
Here is how it looks like in `dav1d`: https://github.com/gdesmott/dav1d-rs/commit/fddf79205c0343ef9970c00149afd9d75f953eab

@sdroege : can you please give it a look and tell me what you think of the API?
I'll open proper MRs when upstreaming (or when I'll create a fork if it goes to that).

**Comment by sdroege** [comment]
Commented on the commit :) Generally looks nice to me.

**Comment by lu-zero** [comment]
Please consider also having a `METADEPS_BUILD_INTERNAL={auto,always,never}` or `METADEPS_BUILD_INTERNAL=all:{auto,always,never}` if the idea of having 1 single env var is still on the plate. The current experience with ssh2-rs clashing with libgit/curl on the tls impl makes me want to have a simple way to override all the behavior w/out having to deal with figuring out the right dependency needing to use pkg-config or do a local build.

**Comment by gdesmott** [comment]
Thanks for the suggestion @lu-zero .
I just added support for `SYSTEM_DEPS_BUILD_INTERNAL` env variable doing exactly that. It's part of the 1.3.0 release.

**Comment by lu-zero** [comment]
Thank you :)
