### ISSUE TITLE
test failed in fedora copr

### ISSUE THREAD

**Issue by remilauzier** [gdesmott/system-deps#42]
https://download.copr.fedorainfracloud.org/results/remilauzier/gtk/fedora-rawhide-x86_64/02305147-rust-system-deps/builder-live.log.gz

**Comment by gdesmott** [comment]
Looks like it doesn't find the files required to run the tests: `src/tests/*/Cargo.toml`.

Is copr doing some kind of out of tree build? Does it help with this patch https://github.com/gdesmott/system-deps/commits/test-path ?

**Comment by remilauzier** [comment]
Can't test directly since fedora take the source from crate.io.

**Comment by gdesmott** [comment]
Can't you run a test build with a specific branch or add a downstream patch? I'd rather not merge this until I'm sure it actually fixes the problem.

**Comment by remilauzier** [comment]
It work!
https://download.copr.fedorainfracloud.org/results/remilauzier/gtk/fedora-rawhide-x86_64/02307637-rust-system-deps/builder-live.log.gz

**Comment by gdesmott** [comment]
Great, thanks for testing!
I just released `3.1.2` with this fix.
