### ISSUE TITLE
Removing dependencies

### ISSUE THREAD

**Issue by GuillaumeGomez** [gdesmott/system-deps#49]
Someone opened an issue on gtk-rs https://github.com/gtk-rs/gtk-rs-core/issues/225 about the fact that this crate was problematic because it weighted heavily on the build process. Would you be open for me to remove dependencies (while keeping the same features!)?

**Comment by gdesmott** [comment]
I'm still not convinced that build specific dependencies are that much of a problem tbh.
That said I may consider simple changes providing they significantly reduce the dependencies tree while not increasing the code complexity or maintenance burden.

Do you know about such potential changes?

**Comment by GuillaumeGomez** [comment]
I opened #50. To answer you, the biggest problem with your crate using a lot of dependencies is that it's used in a lot of places. Now about the dependencies, they have two issues: they need to be downloaded and to be built. And as you know, proc-macro are quite "heavy" on compile-time.

**Comment by sdroege** [comment]
> that it's used in a lot of places

Because of that it's also less of a problem because you only build it once :)
