### ISSUE TITLE
Add support for providing version ranges to pkg-config

### ISSUE THREAD

**Issue by sdroege** [gdesmott/system-deps#60]
This needs calling https://docs.rs/pkg-config/latest/pkg_config/struct.Config.html#method.range_version and some syntax for specifying this in `Cargo.toml`.

**Comment by gdesmott** [comment]
Which syntax should we use for this? The cargo or pkg-config one?

**Comment by sdroege** [comment]
Maybe something that you can parse directly into a range, so maybe just the Rust syntax? `0.1.0..=0.9.0` (for >=0.1.0, <= 0.9.0), `0.1.0..0.9.0` (for >= 0.1.0, << 0.9.0)

**Comment by sdroege** [comment]
Sure if you want to parse those to exact / at least / range

**Comment by sdroege** [comment]
You could use https://docs.rs/semver/latest/semver/ and then convert the result of that to one of the cases pkg-config understands. Converting the `VersionReq` vec of comparators seems like a bit of work though.

**Comment by sdroege** [comment]
I'm working on this now
