### ISSUE TITLE
can't detect library

### ISSUE THREAD

**Issue by TornaxO7** [gdesmott/system-deps#68]
Hello! Thank you for this crate first of all :)

I'm using Arch linux and if I execute the following:
```bash
cd /usr/lib
rg --files | rg libgbm
```
than I'm getting the following output:
```bash
libgbm.so.1.0.0
```
in other words, `/usr/lib/libgbm.so.1.0.0` exist.

But if I have the following in my `Cargo.toml`:
```toml
[package.metadata.system-deps]
libgbm = "1.0.0"
```

I'm getting the following error message, if I try `cargo build`:
```bash
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PkgConfig(`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "libgbm" "libgbm >= 1.0.0"` did not exit successfully: exit status: 1
  error: could not find system library 'libgbm' required by the 'rust_tmp' crate
```

May I ask what I'm doing wrong?

## Reproduction steps
I created a [repository](https://github.com/TornaxO7/system_deps-bug) for you, so you don't need to create directories and stuff through the terminal. Just clone my repository and run `cargo build`. You'll just need to take a look into the [`build.rs`](https://github.com/TornaxO7/system_deps-bug/blob/main/build.rs) and [`Cargo.toml`](https://github.com/TornaxO7/system_deps-bug/blob/main/Cargo.toml#L10-L14) :) I hope it helps!

**Comment by gdesmott** [comment]
`pkg-config` needs the library `.pc` file as well, which is generally provided by `devel` packages (I don't know about Arch).

So you'd need `libgbm.pc` but I checked on my system and I actually have `gbm.pc` so I suppose you should use `gbm` as your dependency.

**Comment by TornaxO7** [comment]
> pkg-config needs the library .pc file as well (...)
so `.pc` *and* `.so` are required or is only `.pc` required?

**Comment by gdesmott** [comment]
yes, you need both to be able to build and link.

**Comment by TornaxO7** [comment]
Alright, thank you for the information!
