### ISSUE TITLE
"no field `ld_args` on type `pkg_config::Library`" on nightly

### ISSUE THREAD

**Issue by dimbleby** [gdesmott/system-deps#94]
running a [CI pipeline](https://github.com/dimbleby/rust-c-ares/actions/runs/9565581214/job/26368816320?pr=108) against nightly rust

```
error[E0609]: no field `ld_args` on type `pkg_config::Library`
    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/system-deps-7.0.0/src/lib.rs:1068:24
     |
1068 |             ld_args: l.ld_args,
     |                        ^^^^^^^ unknown field
     |
     = note: available fields are: `libs`, `link_paths`, `frameworks`, `framework_paths`, `include_paths` ... and 2 others

For more information about this error, try `rustc --explain E0609`.
error: could not compile `system-deps` (lib) due to 1 previous error
```
maybe you already know about this, maybe this is a nightly rust problem and not a system-deps problem, certainly it's not important to me so long as it is happening only on nightly - but I figured I should let you know about it in case work is needed

**Comment by gdesmott** [comment]
Thanks for the info, I was not aware of this problem.

That's really strange, why would [`Library.ld_args`](https://docs.rs/pkg-config/latest/pkg_config/struct.Library.html#structfield.ld_args) be missing with nightly?

@sdroege @amyspark : any idea?

**Comment by sdroege** [comment]
I don't know. It's always there since pkg-config-rs 0.3.24. Maybe that CI is using an ancient pkg-config-rs version?

**Comment by gdesmott** [comment]
Good point, we should have bumped the minimal version required!

Looks like it's from `0.3.25` actually.

**Comment by dimbleby** [comment]
ah yes, I also test with minimal versions - I hadn't realised that was the specific test that was failing

thanks!
